# server
server.port=8080
app.base-url=http://51.250.100.129:8080

# database
db.driver=org.postgresql.Driver
db.url=jdbc:postgresql://localhost:5432/weatherdb
db.username=weatheruser
db.password=weatherpass123

# hibernate
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.show_sql=false
hibernate.hbm2ddl.auto=validate

# flyway
flyway.locations=classpath:db/migration
flyway.baselineOnMigrate=true

# weather api
weather.api.key=dcb61c4a097410d2bbc07433ea7c7f47